"use client";

import { useState } from "react";

type Settings = { masked_hint?: string | null; validated_at?: string | null; config?: { model?: string; fallbackModel?: string | null; promptVersion?: string; maxCostUsd?: number } } | null;

export function IntegrationSettings({ initial }: { initial: Settings }) {
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [masked, setMasked] = useState(initial?.masked_hint);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); const form = new FormData(event.currentTarget); const key = String(form.get("apiKey") ?? "").trim(); const response = await fetch("/api/admin/integrations/openrouter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ apiKey: key || undefined, model: form.get("model"), fallbackModel: form.get("fallbackModel") || undefined, promptVersion: form.get("promptVersion"), maxCostUsd: Number(form.get("maxCostUsd")) }) }); const payload = await response.json(); setLoading(false); if (!response.ok) return setMessage(payload.error?.message ?? "Não foi possível salvar."); setMasked(payload.data.masked_hint); setMessage("Configuração validada e protegida no Vault."); (event.currentTarget.elements.namedItem("apiKey") as HTMLInputElement).value = ""; }
  return <><div className="live-page-heading"><div><p className="eyebrow">CONFIGURAÇÃO PROTEGIDA</p><h1>Integrações</h1><p>A chave é escrita diretamente no Vault e nunca poderá ser consultada novamente pela interface.</p></div>{masked && <span className="live-account-count">OpenRouter {masked}</span>}</div><div className="integration-grid"><form className="integration-card" onSubmit={submit}><header><span>AI</span><div><h2>OpenRouter</h2><p>Triagem documental estruturada, sempre sujeita à decisão humana.</p></div></header><label>Nova chave secreta<input name="apiKey" type="password" autoComplete="new-password" placeholder={masked ? "Deixe vazio para manter a chave atual" : "sk-or-…"} required={!masked}/></label><label>Modelo principal<input name="model" defaultValue={initial?.config?.model ?? "google/gemini-2.5-flash"} required /></label><label>Modelo de fallback<input name="fallbackModel" defaultValue={initial?.config?.fallbackModel ?? ""} /></label><div><label>Versão do prompt<input name="promptVersion" defaultValue={initial?.config?.promptVersion ?? "urus-doc-v1"} required /></label><label>Limite por análise (USD)<input name="maxCostUsd" type="number" min="0.01" max="100" step="0.01" defaultValue={initial?.config?.maxCostUsd ?? 0.25} required /></label></div>{message && <p className="live-form-message">{message}</p>}<button className="live-gold-button" disabled={loading}>{loading ? "Validando…" : "Salvar configuração"}</button></form><aside className="integration-risk"><p className="eyebrow">RISCO OPERACIONAL ATUAL</p><h2>Antivírus ainda não habilitado</h2><p>Os uploads reais estão liberados conforme a decisão atual, com verificação de tipo, assinatura binária, tamanho e checksum. Isso não substitui varredura contra malware.</p><ul><li>Storage privado e caminhos aleatórios</li><li>URLs temporárias e acesso auditado</li><li>Serviço de malware preparado para ativação</li></ul></aside></div></>;
}
